sudo: required
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

notifications:
  email:
    on_success: never

install:
  - pip install -r requirements.txt
  - pip install pytest-cov python-coveralls

script:
  - python --version
  - export PYTHONPATH=$PWD/:$PYTHONPATH
  - py.test --cov=catlearn test/test_suite.py

after_success:
  - coveralls
